### ISSUE TITLE
[tacoshack] It'd be great not to have the `t` as an alias.

### ISSUE THREAD

**Issue by Cool-aid-man** [jmesfo0/jmes-cogs#1]
Hey!
James, hope you're doing great! Love your `tacoshack` cog, it's so good. And being able to play taco through your own bot makes it even more fun.
**Thank you for the cog.**

> I was just wondering if you could remove one of the default alias `t` from the list of alias, as it's messing up with other cogs that has the cmd already and are more important in a way.
> I think it'd be great to have the cog without the `t` as a **default** alias, one can add it if they like, and removing `t` won't make it harder either.

Thanks and looking forward to see the franchisee implementation on `tacoshack` cog in future. :)
Have a great day ahead.

**Comment by jmesfo0** [comment]
Oh awesome somebody is using my cog I love it! I'm glad you like it I will implement the changes right away and remove the t alias

**Comment by jmesfo0** [comment]
I have removed the 't' alias for now I will make updates in the future I went off TacoShack-classic and it was written it nodejs so it was a little tricky. The hourly income needs to be fixed as well it gives hourly income everytime you reload the cog right now I want to turn it into a cron task on the hour

**Comment by Cool-aid-man** [comment]
Thank you, James, and yes, getting the timer for hourly income on cron should solve the issue.
It'd also help with the cmds like `overtime` for **franchise** when you're able to implement that.
Thanks again!
